[package]
name = "flowforge"
version = "0.1.0"
edition = "2021"

[dependencies]
enum_dispatch = "0.3.11"
linked-hash-map = "0.5.6"
regex = "1.7.1"
serde_yaml = "0.9.19"
thiserror = "1.0.39"

[dev-dependencies]
pretty_assertions = "1.3.0"
